---
# file: practice/1.kube-basics-lecture/1.3.pod/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - image: busybox:latest
    name: hello-cont
    command: ['sh', '-c', 'while true; do echo New random number is $(( ( RANDOM % 100 ) + 1 )); sleep 2; done']
    ports:
    - containerPort: 80
...
