apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: teams.ops.southbridge.io
spec:
  conversion:
    strategy: None
  group: ops.southbridge.io
  names:
    kind: Team
    listKind: TeamList
    plural: teams
    singular: team
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Person incharged for the team's environments
      jsonPath: .spec.inCharge
      name: In charge
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              environments:
                type: array
                items:
                  type: object
                x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
